// <auto-generated />
using BazaPoklona.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BazaPoklona.Migrations
{
    [DbContext(typeof(BazaPoklonaContext))]
    partial class BazaPoklonaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Croatian_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BazaPoklona.Models.OstvareniPromet", b =>
                {
                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Naziv");

                    b.Property<double>("UkupnoLovePoVrstiRobe")
                        .HasColumnType("float")
                        .HasColumnName("UkupnoLovePoVrstiRobe");

                    b.Property<string>("VrstaRobe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VrstaRobe");

                    b.ToView("View_OstvareniPromet");
                });

            modelBuilder.Entity("BazaPoklona.Models.OstvareniPrometViewModel", b =>
                {
                    b.Property<string>("NazivRobe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("UkupnoLovePoVrstiRobe")
                        .HasColumnType("float");

                    b.Property<string>("VrstaRobe")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("OstvareniPrometViewModels");
                });

            modelBuilder.Entity("BazaPoklona.Models.Poklon", b =>
                {
                    b.Property<int>("IdPoklon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cijena")
                        .HasColumnType("float");

                    b.Property<bool>("Kupljen")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("VrstaRobe")
                        .HasColumnType("int");

                    b.HasKey("IdPoklon")
                        .HasName("PK__Poklon__2D443D4D5AEE092A");

                    b.HasIndex("VrstaRobe");

                    b.ToTable("Poklon");
                });

            modelBuilder.Entity("BazaPoklona.Models.Trgovina", b =>
                {
                    b.Property<int>("IdTrgovina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivTrgovina")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("VrstaRobe")
                        .HasColumnType("int");

                    b.HasKey("IdTrgovina")
                        .HasName("PK__Trgovina__A41276705583ABF8");

                    b.HasIndex("VrstaRobe");

                    b.ToTable("Trgovina");
                });

            modelBuilder.Entity("BazaPoklona.Models.VrstaRobe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("VrstaRobe");
                });

            modelBuilder.Entity("BazaPoklona.Models.Poklon", b =>
                {
                    b.HasOne("BazaPoklona.Models.VrstaRobe", "VrstaRobeNavigation")
                        .WithMany("Poklons")
                        .HasForeignKey("VrstaRobe")
                        .HasConstraintName("FK__Poklon__VrstaRob__286302EC")
                        .IsRequired();

                    b.Navigation("VrstaRobeNavigation");
                });

            modelBuilder.Entity("BazaPoklona.Models.Trgovina", b =>
                {
                    b.HasOne("BazaPoklona.Models.VrstaRobe", "VrstaRobeNavigation")
                        .WithMany("Trgovinas")
                        .HasForeignKey("VrstaRobe")
                        .HasConstraintName("FK__Trgovina__VrstaR__29572725")
                        .IsRequired();

                    b.Navigation("VrstaRobeNavigation");
                });

            modelBuilder.Entity("BazaPoklona.Models.VrstaRobe", b =>
                {
                    b.Navigation("Poklons");

                    b.Navigation("Trgovinas");
                });
#pragma warning restore 612, 618
        }
    }
}
